controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# config/routes.yaml
profile:
    path: /profile/{id}
    controller: App\Controller\ProfileController::show
    requirements:
        id: \d+
